### ISSUE TITLE
Compilation error in NMEA2000_mcp.cpp

### ISSUE THREAD

**Issue by OzOns** [ttlappalainen/NMEA2000_mcp#1]
Hi Timo,

Maybe I am fool, rookie for sure :-) 

\Arduino\libraries\NMEA2000_mcp-master\NMEA2000_mcp.cpp: In constructor 'tNMEA2000_mcp::tNMEA2000_mcp(unsigned char, unsigned char, unsigned char, uint16_t)':

\Arduino\libraries\NMEA2000_mcp-master\NMEA2000_mcp.cpp:71:20: error: cannot convert 'tNMEA2000::tCANFrame_' to 'volatile tCANFrame_' in assignment

```
   rx_frame_buff=new tCANFrame[rx_frame_buf_size];

                ^
```

Cheers

**Comment by ttlappalainen** [comment]
Sorry, my mistake. Please reload NMEA2000 library, where I renamed some definitions to avoid this conflict.

**Comment by OzOns** [comment]
It works !

Thks Timo. Have a nice day :-)
